name: CI
on: [push, pull_request]
jobs:
  typst:
    name: Typst
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Install font dependencies
        run: |
          sudo apt update || true
          sudo apt --yes --no-install-recommends install fonts-inconsolata
          wget https://github.com/alerque/libertinus/releases/download/v7.051/Libertinus-7.051.zip
          unzip -d fonts/ Libertinus-7.051.zip
      - name: Install Typst via Release Download
        run: |
          wget https://github.com/typst/typst/releases/download/v0.15.0/typst-x86_64-unknown-linux-musl.tar.xz
          mkdir ~/typst && tar -xf typst-x86_64-unknown-linux-musl.tar.xz -C ~/typst
          echo "$HOME/typst/typst-x86_64-unknown-linux-musl" >> $GITHUB_PATH
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Copy templates into local namespace
        run: |
          THESIS_VERSION="$(grep version thesis-typst/typst.toml | grep -E '[0-9]+.[0-9]+.[0-9]+' -o)"
          SLIDES_VERSION="$(grep version presentation-typst/typst.toml | grep -E '[0-9]+.[0-9]+.[0-9]+' -o)"
          mkdir -p ~/.local/share/typst/packages/local/parcio-thesis/$THESIS_VERSION && cp -r thesis-typst/* $_
          mkdir -p ~/.local/share/typst/packages/local/parcio-slides/$SLIDES_VERSION && cp -r presentation-typst/* $_
      - name: Build thesis
        run: typst compile thesis-typst/template/thesis.typ thesis-typst/thesis.pdf --font-path ./fonts
      - name: Build presentation
        run: typst compile presentation-typst/template/slides.typ presentation-typst/slides.pdf --font-path ./fonts        
      - name: Prepare directory
        run: |
          mkdir -p public/typst
          cp thesis-typst/thesis.pdf public/typst
          cp presentation-typst/slides.pdf public/typst
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: typst-artifact
          path: public
          retention-days: 1
          
  latex:
    name: LaTeX
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Install dependencies
        run: |
          sudo apt update || true
          sudo apt --yes --no-install-recommends install texlive texlive-fonts-extra texlive-lang-german texlive-latex-extra texlive-plain-generic latexmk
          sudo apt --yes --no-install-recommends install ghostscript imagemagick
      - name: Allow PDF conversions
        # FIXME Ubuntu has blocked PDF conversions in ImageMagick for security reasons
        run: |
          sudo sed --in-place '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Build presentation
        run: |
          cd presentation-latex
          latexmk -pdf presentation.tex
      - name: Build report
        run: |
          cd report-latex
          latexmk -pdf report.tex
      - name: Build thesis
        run: |
          cd thesis-latex
          latexmk -pdf thesis.tex
      - name: Create thumbnails
        run: |
          convert -colorspace sRGB -density 300 -thumbnail 1920x1920 -quality 90 -background white -alpha remove -alpha off 'presentation-latex/presentation.pdf[0]' presentation-latex/presentation.png
          convert -colorspace sRGB -density 300 -thumbnail 1920x1920 -quality 90 -background white -alpha remove -alpha off 'report-latex/report.pdf[0]' report-latex/report.png
          convert -colorspace sRGB -density 300 -thumbnail 1920x1920 -quality 90 -background white -alpha remove -alpha off 'thesis-latex/thesis.pdf[0]' thesis-latex/thesis.png
      - name: Prepare directory
        run: |
          mkdir -p public/latex
          cp presentation-latex/presentation.pdf presentation-latex/presentation.png public/latex
          cp report-latex/report.pdf report-latex/report.png public/latex
          cp thesis-latex/thesis.pdf thesis-latex/thesis.png public/latex
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: latex-artifact
          path: public
          retention-days: 1

  combine:
    name: Combine Artifacts
    needs: [typst, latex]
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: public
          merge-multiple: true
      - name: Upload combined artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: public
          
  deploy:
    name: Deploy
    needs: combine
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
